### ISSUE TITLE
Комментарии к заявке

### ISSUE THREAD

**Issue by aakuptsov** [ReznikovRoman/Project#1]
1. >>Напоминания о необходимости купить недостающие продукты в магазине

Каким образом программа будет знать, что у пользователя в холодильнике?

2. >>Визуализация рецептов

Что именно визуализируется: приготовленное блюдо? Ингредиенты? Процесс приготовления?

3. >>Создание профиля в приложении

С какой целью даётся такая возможность?

4. >>Выбор тарифных планов и способов оплаты

Плата взимается за пользование приложение в целом или за какие-то отдельные функции?

5. Где будут храниться рецепты? Хардкодить их недопустимо. 

6. Обязательно должна быть админка для добавления рецептов.

7. В целом, оригинальность проекта вызывает сомнение, поскольку как минимум 2 подобных проекта защищалось в 2018 году; к тому же, есть и другие приложения.

**Comment by aakuptsov** [comment]
15 января - ответов на вопросы нет.

**Comment by ReznikovRoman** [comment]
> 
> 
>     1. > > Напоминания о необходимости купить недостающие продукты в магазине
> 
> 
> Каким образом программа будет знать, что у пользователя в холодильнике?

> У каждого рецепта будут свои ингредиенты. Пользователь выбирает в фильтре, какие ингредиенты есть у него в холодильнике. Приложение "выдает" ему список подходящих блюд, с нужными ему ингредиентами, но если у пользователя не будет какого-либо рецепта, он будет иметь возможность добавить этот ингредиент в корзину и установить напоминание о покупке.
>     1. > > Визуализация рецептов
> 
> 
> Что именно визуализируется: приготовленное блюдо? Ингредиенты? Процесс приготовления?

> Визуализируется готовое блюдо. (Возможно, в дальнейшем появится фото блюда на разных этапах процесса приготовления)
>     1. > > Создание профиля в приложении
> 
> 
> С какой целью даётся такая возможность?

> Пользователь сможет предлагать внести изменения или предлагать собственные рецепты. 
>     1. > > Выбор тарифных планов и способов оплаты
> 
> 
> Плата взимается за пользование приложение в целом или за какие-то отдельные функции?

> Тарифных планов не будет, приложение будет полностью бесплатным.
>     1. Где будут храниться рецепты? Хардкодить их недопустимо.

> Я еще думаю над этим вопросом.
>     2. Обязательно должна быть админка для добавления рецептов.
> 
>     3. В целом, оригинальность проекта вызывает сомнение, поскольку как минимум 2 подобных проекта защищалось в 2018 году; к тому же, есть и другие приложения.

 А что с этим пунктом делать? Мне нужно придумать еще какие-нибудь функции или нужно сменить тему проекта?

**Comment by aakuptsov** [comment]
>>Мне нужно придумать еще какие-нибудь функции или нужно сменить тему проекта?

Да, что-то одно из этих двух.

Чисто теоретически, ты можешь продолжать этот проект, но, боюсь, что по критерию "оригинальность" он получит 0.

**Comment by ReznikovRoman** [comment]
> 
> 
> > > Мне нужно придумать еще какие-нибудь функции или нужно сменить тему проекта?
> 
> Да, что-то одно из этих двух.
> 
> Чисто теоретически, ты можешь продолжать этот проект, но, боюсь, что по критерию "оригинальность" он получит 0.

Хорошо, буду думать. 
А до какого числа еще можно вносить изменения в заявку?

**Comment by aakuptsov** [comment]
Там на какое-то число назначена комиссия, я не помню, если честно, просто я комиссий делать не хочу, просто дальше работаем над заявками и всё.

Однако, скоро я объявлю следующий этап работы над проектами (пользовательские сценарии), поэтому лучше поторопиться :) 

В любом случае задолженность по ИВР по сути означает, что идея проекта пока не развита. Поэтому волноваться не стоит, а просто надо ещё чуть-чуть подумать :)

**Comment by ReznikovRoman** [comment]
> 
> 
> Там на какое-то число назначена комиссия, я не помню, если честно, просто я комиссий делать не хочу, просто дальше работаем над заявками и всё.
> 
> Однако, скоро я объявлю следующий этап работы над проектами (пользовательские сценарии), поэтому лучше поторопиться :)
> 
> В любом случае задолженность по ИВР по сути означает, что идея проекта пока не развита. Поэтому волноваться не стоит, а просто надо ещё чуть-чуть подумать :)

Хорошо

**Comment by aakuptsov** [comment]
Какое принял решение по проекту (см. нашу переписку выше).

**Comment by aakuptsov** [comment]
21 января - незачёт

**Comment by aakuptsov** [comment]
Зачёт условно. Вынесено предупреждение о возможной неоригинальности продукта. Есть отдельные второстепенные фичи, которые, возможно, выделяют продукт из основных.
